--
-- turbine-security-data.sql
-- profilo basilare di sicurezza per consentire una login al sistema
--

INSERT INTO TURBINE_USER (USER_ID,LOGIN_NAME,PASSWORD_VALUE,FIRST_NAME,LAST_NAME)
    VALUES (0,'turbine', 'turbine','','Turbine');

INSERT INTO TURBINE_USER (USER_ID,LOGIN_NAME,PASSWORD_VALUE,FIRST_NAME,LAST_NAME)
    VALUES (1,'admin','password','','Admin');

INSERT INTO TURBINE_USER (USER_ID,LOGIN_NAME,PASSWORD_VALUE,FIRST_NAME,LAST_NAME)
    VALUES (2,'user','password','','User');

INSERT INTO TURBINE_USER (USER_ID,LOGIN_NAME,PASSWORD_VALUE,FIRST_NAME,LAST_NAME)
    VALUES (3,'anon','nopw','','Anon');


INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (1, 'TurbineAdmin');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (2, 'Turbine');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (3, 'Internal');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (4, 'Portal');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (5, 'shAngelPerm');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID, PERMISSION_NAME) VALUES (6, 'bypassPreventivi');

INSERT INTO TURBINE_ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'turbine_root');
INSERT INTO TURBINE_ROLE (ROLE_ID, ROLE_NAME) VALUES (2, 'internaluser');
INSERT INTO TURBINE_ROLE (ROLE_ID, ROLE_NAME) VALUES (3, 'portaluser');
INSERT INTO TURBINE_ROLE (ROLE_ID, ROLE_NAME) VALUES (4, 'shoppingangel');

INSERT INTO TURBINE_GROUP (GROUP_ID, GROUP_NAME) VALUES (1, 'global');

INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 2);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 3);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 4);

INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 3);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 4);

INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (3, 4);

INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 5);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 6);

INSERT INTO TURBINE_USER_GROUP_ROLE (USER_ID, GROUP_ID, ROLE_ID) VALUES (0, 1, 1);
INSERT INTO TURBINE_USER_GROUP_ROLE (USER_ID, GROUP_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO TURBINE_USER_GROUP_ROLE (USER_ID, GROUP_ID, ROLE_ID) VALUES (2, 1, 2);
INSERT INTO TURBINE_USER_GROUP_ROLE (USER_ID, GROUP_ID, ROLE_ID) VALUES (3, 1, 3);

