/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensc_SchedStamper */

#ifndef _Included_org_opensc_SchedStamper
#define _Included_org_opensc_SchedStamper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensc_SchedStamper
 * Method:    openNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedStamper_openNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedStamper
 * Method:    closeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedStamper_closeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedStamper
 * Method:    buildNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedStamper_buildNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
