/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensc_SchedMerger */

#ifndef _Included_org_opensc_SchedMerger
#define _Included_org_opensc_SchedMerger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensc_SchedMerger
 * Method:    openNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_openNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    closeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_closeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    dumpSlotsNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedMerger_dumpSlotsNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    getMergerAlgosNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedMerger_getMergerAlgosNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    mergeResourcesNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_mergeResourcesNative
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    getResourcesListNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedMerger_getResourcesListNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    clearResourcesNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_clearResourcesNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    reserveSlotNative
 * Signature: (IIJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_reserveSlotNative
  (JNIEnv *, jobject, jint, jint, jlong, jstring);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    getInfoHeaderNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedMerger_getInfoHeaderNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    findFreeSlotNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedMerger_findFreeSlotNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    clearSlotNative
 * Signature: (IIJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedMerger_clearSlotNative
  (JNIEnv *, jobject, jint, jint, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
