/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensc_SchedResource */

#ifndef _Included_org_opensc_SchedResource
#define _Included_org_opensc_SchedResource
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opensc_SchedResource_SLOT_UNAVAILABLE
#define org_opensc_SchedResource_SLOT_UNAVAILABLE 0L
#undef org_opensc_SchedResource_SLOT_SCHEDULABLE
#define org_opensc_SchedResource_SLOT_SCHEDULABLE 1L
#undef org_opensc_SchedResource_SLOT_LOOKED
#define org_opensc_SchedResource_SLOT_LOOKED 2L
#undef org_opensc_SchedResource_SLOT_BOOKED
#define org_opensc_SchedResource_SLOT_BOOKED 3L
/*
 * Class:     org_opensc_SchedResource
 * Method:    setDebugMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedResource_setDebugMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opensc_SchedResource
 * Method:    openNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedResource_openNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedResource
 * Method:    closeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedResource_closeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedResource
 * Method:    buildNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedResource_buildNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedResource
 * Method:    clearAllSlotsNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedResource_clearAllSlotsNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_opensc_SchedResource
 * Method:    stampResourcesNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_opensc_SchedResource_stampResourcesNative
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_opensc_SchedResource
 * Method:    getStamperAlgosNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedResource_getStamperAlgosNative
  (JNIEnv *, jobject);

/*
 * Class:     org_opensc_SchedResource
 * Method:    dumpHeaderNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedResource_dumpHeaderNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opensc_SchedResource
 * Method:    dumpSlotsNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensc_SchedResource_dumpSlotsNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
