/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensc_SchedMerger */

#ifndef _Included_org_opensc_SchedMerger
#define _Included_org_opensc_SchedMerger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensc_SchedMerger
 * Method:    openNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedMerger_openNative(JNIEnv *, jobject,
                                                              jstring);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    closeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedMerger_closeNative(JNIEnv *,
                                                               jobject);

/*
 * Class:     org_opensc_SchedMerger
 * Method:    buildNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensc_SchedMerger_buildNative(JNIEnv *,
                                                               jobject,
                                                               jstring);

#ifdef __cplusplus
}
#endif
#endif
