package org.opensc.agenda.om;


/**
 * Maps ResultSet rows into Book objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 10:40:10 CEST 2026]
 *
 */
public class BookRecordMapper extends BaseBookRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1786610410990L;



}
