package org.opensc.agenda.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 17 12:06:34 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Eventi
    extends org.opensc.agenda.om.BaseEventi
{
    /** Serial version */
    private static final long serialVersionUID = 1786961194539L;



}
