package org.opensc.agenda.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 17 12:06:35 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class EventiPeerImpl
    extends org.opensc.agenda.om.BaseEventiPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1786961195394L;



}
