package org.opensc.agenda.om;

import java.util.Date;
import org.apache.torque.TorqueException;
import org.commonlib5.utils.DateTime;
import org.commonlib5.utils.StringJoin;
import org.commonlib5.utils.StringOper;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 17 12:06:34 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class Eventi
   extends org.opensc.agenda.om.BaseEventi
{
  /** Serial version */
  private static final long serialVersionUID = 1786961194539L;

  @Override
  public boolean setByName(String name, Object value)
     throws TorqueException, IllegalArgumentException
  {
    if(name.equals("EventiId"))
    {
      int val = StringOper.parse(value, getEventiId());
      setEventiId(val);
      return true;
    }
    if(name.equals("IdCalendar"))
    {
      int val = StringOper.parse(value, getIdCalendar());
      setIdCalendar(val);
      return true;
    }
    if(name.equals("Title"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setTitle((String) value);
      return true;
    }
    if(name.equals("Body"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setBody((String) value);
      return true;
    }
    if(name.equals("Category"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setCategory((String) value);
      return true;
    }
    if(name.equals("Isreadonly"))
    {
      boolean val = StringOper.checkTrueFalse(value, isIsreadonly());
      setIsreadonly(val);
      return true;
    }
    if(name.equals("Isprivate"))
    {
      boolean val = StringOper.checkTrueFalse(value, isIsreadonly());
      setIsprivate(val);
      return true;
    }
    if(name.equals("Elocation"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setElocation((String) value);
      return true;
    }
    if(name.equals("Attendees"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setAttendees((String) value);
      return true;
    }
    if(name.equals("Recurrencerule"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setRecurrencerule((String) value);
      return true;
    }
    if(name.equals("Estate"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setEstate((String) value);
      return true;
    }
    if(name.equals("Goingduration"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setGoingduration((String) value);
      return true;
    }
    if(name.equals("Comingduration"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setComingduration((String) value);
      return true;
    }
    if(name.equals("Startdate"))
    {
      setStartdate(parseDate(value, getStartdate()));
      return true;
    }
    if(name.equals("Enddate"))
    {
      setEnddate(parseDate(value, getEnddate()));
      return true;
    }
    if(name.equals("Eraw"))
    {
      // Object fields can be null
      if(value != null && !String.class.isInstance(value))
      {
        throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
      }
      setEraw((String) value);
      return true;
    }
    return false;
  }

  private Date parseDate(Object value, Date defVal)
  {
    long tempo = DateTime.convertDateCommonFormat(StringOper.okStr(value));

    if(tempo == 0)
      return defVal;

    return new Date(tempo);
  }

  public String[] getAttendeesArray()
  {
    return StringOper.string2Array(getAttendees(), ",");
  }

  public void setAttendeesArray(String[] valori)
  {
    setAttendees(StringJoin.build().add(valori).join());
  }
}
