package org.opensc.agenda.om;


/**
 * Maps ResultSet rows into Eventi objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 17 12:06:35 CEST 2026]
 *
 */
public class EventiRecordMapper extends BaseEventiRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1786961195874L;



}
