package org.opensc.agenda.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 27 17:33:02 CEST 2026]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class PrenotazioniPeer
   extends org.opensc.agenda.om.BasePrenotazioniPeer
{

}
