package org.opensc.agenda.om;


/**
 * Maps ResultSet rows into Prenotazioni objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 27 17:33:02 CEST 2026]
 *
 */
public class PrenotazioniRecordMapper extends BasePrenotazioniRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1787844782637L;



}
