package org.opensc.agenda.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 27 17:33:02 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class PrenotazioniLinkPeerImpl
    extends org.opensc.agenda.om.BasePrenotazioniLinkPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1787844782205L;



}
