package org.opensc.agenda.om;

import java.sql.Connection;
import java.util.List;
import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.criteria.SqlEnum;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 18:11:58 CEST 2026]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class PrestazioniPeer
   extends org.opensc.agenda.om.BasePrestazioniPeer
{
  public static Prestazioni retrieveByCodice(String codPrest, Connection con)
     throws TorqueException
  {
    Criteria c = new Criteria();
    c.where(PRESTAZIONI_ID, 0, SqlEnum.GREATER_THAN);
    c.addAscendingOrderByColumn(PRESTAZIONI_ID);
    List<Prestazioni> ls = doSelect(c, con);
    return ls.isEmpty() ? null : ls.get(0);
  }
}
