package org.opensc.agenda.om;


/**
 * Maps ResultSet rows into RisorseLink objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 18:11:59 CEST 2026]
 *
 */
public class RisorseLinkRecordMapper extends BaseRisorseLinkRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1786637519011L;



}
