package org.opensc.agenda.om;


/**
 * Maps ResultSet rows into TurbineRolePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 10:40:10 CEST 2026]
 *
 */
public class TurbineRolePermissionRecordMapper extends BaseTurbineRolePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1786610410996L;



}
