package org.opensc.agenda.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 10:40:10 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineGroupPeerImpl
    extends org.opensc.agenda.om.BaseTurbineGroupPeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbinePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1786610410757L;



}
