package org.opensc.agenda.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 13 10:40:10 CEST 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbineGroup
    extends org.opensc.agenda.om.BaseTurbineGroup
    implements org.apache.fulcrum.security.model.turbine.entity.TurbineGroup
{
    /** Serial version */
    private static final long serialVersionUID = 1786610410265L;



}
